Comments- needed to be added
"pip install python-whois"

not "pip install whois"

Else it will give :"AttributeError: 'module' object has no attribute 'whois'"